demo/urls.py
from django.urls import path
from demo import views
from demo.views import TrainerCreateView, TrainerUpdateView
app_name = "demo"

urlpatterns = [
    path('home', views.home, name = 'home'),
    # path('', views.home, name = 'home'),
    path('blog', views.blog, name = 'blog'),
    path('about', views.about, name = 'about'),
    path('portfolio', views.portfolio, name = 'portfolio'),
    path('contact', views.contact, name = 'contact'),
    path('blogsingle/<id>', views.blogsingle, name = 'blogsingle'),
    path('training', views.training, name = 'training'),
    path('trainingdetails/<id>', views.trainingdetails, name = 'trainingdetails'),
    path('TrainerCreateView', TrainerCreateView.as_view(), name = 'TrainerCreateView'),
    path('<pk>/trainer', TrainerUpdateView.as_view(), name = 'trainer'),
]


# home, about, blog, portfolio, contact, blogsingle

library/urls.py
from django.contrib import admin
from django.urls import path
from library import views     

from .views import Forms, StudentList, StudentDetail, StudentUpdate, StudentDelete

app_name = "library"
urlpatterns = [
    
    
    path('home', views.home, name = 'home'),
    path('forms', Forms.as_view(), name = 'forms'),
    path('list', StudentList.as_view(), name = 'list'),
    path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
    path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
    path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),
    
    
    
]

tempaltedemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from demo import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls', namespace = 'demo')),
    path('', views.home, name = 'home'),
    # path('', views.home, name = 'home'),
    path('library/', include('library.urls', namespace = 'library')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('landingpage/', include('landingpage.urls', namespace = 'landingpage')),
    path('photography/', include('photography.urls', namespace = 'photography')),
    path('restaurant/', include('restaurant.urls', namespace = 'restaurant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models

# Create your models here.
class StudentDetails(models.Model):
    NoOfYears = (
        ('i', 'First Yesr'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
    )
    Stu_name = models.CharField(max_length = 200)
    department = models.CharField(max_length = 50)
    year = models.CharField(max_length = 1, choices = NoOfYears, default = 1)
    book = models.CharField(max_length = 100)
    Author = models.CharField(max_length = 100)
    BookNumber = models.IntegerField()
    Issued_date = models.DateField(auto_now_add = True)
    returned  = models.BooleanField(default = False)
    returned_date = models.CharField(max_length = 20, null = True, blank = True)
    def __str__(self):
        return self.Stu_name

library/forms.py
from django.forms import forms, ModelForm
from .models import StudentDetails

class StudentDetailsForm(ModelForm):
    class Meta:
        models = StudentDetails
        fields = "__all__"

library/views.py
from django.shortcuts import render, redirect

from .models import StudentDetails
from .forms import StudentDetailsForm

from django.urls import reverse_lazy

# Create your views here.
def home(request):
    student = StudentDetails.objects.all()
    context = {'student':student}
    return render(request, 'library/home.html', context)
    # return redirect(reverse_lazy("library:home")) 



from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

class Forms(CreateView):
    model = StudentDetails
    fields = "__all__"
    template_name = 'library/cbv/forms.html'
    success_url = '/'

class StudentList(ListView):
    model = StudentDetails
    template_name = 'library/cbv/stulist.html'

class StudentDetail(DetailView):
    model = StudentDetails
    template_name = 'library/cbv/studetail.html'

class StudentUpdate(UpdateView):
    model = StudentDetails
    fields = '__all__'
    template_name = 'library/cbv/stuupdate.html'
    success_url = '/'

class StudentDelete(DeleteView):
    model = StudentDetails
    template_name = 'library/cbv/studelete.html'
    success_url = '/'

library/templates/library/home.html
{% extends 'base1.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/style1.css' %}" rel="stylesheet">
    <style>
        table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }

  .button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 30px;
  }
  
  .button2 {background-color: #008CBA;} /* Blue */
  .button3 {background-color: #f44336;} /* Red */ 
  .button4 {background-color: #e7e7e7; color: black;} /* Gray */ 
  .button5 {background-color: #555555;} /* Black */
    </style>
</head>



<body>


    
    {% block title %}


    
<!-- page title -->
<section class="page-title bg-primary position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="text-white font-tertiary">Library Page.</h1>
        </div>
      </div>
    </div>
    <!-- background shapes -->
    <img src="{% static 'images/illustrations/page-title.png' %}" alt="illustrations" class="bg-shape-1 w-100">
    <img src="{% static 'images/illustrations/leaf-pink-round.png' %}" alt="illustrations" class="bg-shape-2">
    <img src="{% static 'images/illustrations/dots-cyan.png' %}" alt="illustrations" class="bg-shape-3">
    <img src="{% static 'images/illustrations/leaf-orange.png' %}" alt="illustrations" class="bg-shape-4">
    <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-5">
    <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-6">
    <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-7">
  </section>
  <!-- /page title -->
  
  <!-- portfolio -->
  
  <!-- <section class="section">
    <div class="container">
     
    </div>
  </section>
   -->

  <!-- /portfolio -->
  

  <!-- clients -->
  <section class="section bg-light">
    <div class="container">
        <h1><a href="{% url 'library:forms' %}">Click here to create an Entry.</a></h1>
      <div class="row">
        <div class="col-12 text-center">
          <h2 class="section-title">Students Books List</h2>
        </div>
      </div>
      <div class="row">
        
          
           
    

                <!-- <table>
                    <tr>
                        <th>Name</th>
                        <th>Department</th>
                        <th>Year</th>
                        <th>Book</th>
                        <th>Author</th>
                        <th>Book Number</th>
                        <th>Issued Date</th>
                        <th>Book Returned</th>
                        <th>Book Returned Date</th>
                        <th>Details</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    {% for object in student %}                    
                            <tr>
                                <td>{{object.Stu_name}}</td>
                                <td> {{object.department}}</td>
                                <td>{{object.year}}</td>
                                <td>{{object.book}}</td>
                                <td>{{object.Author}}</td>
                                <td>{{object.BookNumber}}</td>
                                <td>{{object.Issued_date}}</td>
                                <td>{{object.returned}}</td>
                                <td>{{object.returned_data}}</td>
                                <td><a type="button" class="btn btn-primary" href= "{{object.id}}/detail">Detail</a></td>
                                <td><a type=" button " class = "btn btn-success" href ="{{object.id}}/update" >Update</a>
                                <td><a type = "button" class="btn btn-danger" href="{{object.id}}/delete">Delete</a></td>
                            </tr>                           
                            
                    {% endfor %}             
        
                </table>
This is the new table. -->
                <table class="table table-striped">
                    <thead class="thead-dark">
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Department</th>
                        <th scope="col">Year</th>
                        <th scope="col">Book</th>
                        <th scope="col">Author</th>
                        <th scope="col">Book Number</th>
                        <th scope="col">Issued Date</th>
                        <th scope="col">Book Returned</th>
                        <th scope="col">Book Returned Date</th>
                        <th scope="col">Details</th>
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for object in student %}
                      <tr>
                        
                        <td>{{object.Stu_name}}</td>
                        <td>{{object.department}}</td>
                        <td>{{object.year}}</td>
                        <td>{{object.book}}</td>
                        <td>{{object.Author}}</td>
                        <td>{{object.BookNumber}}</td>
                        <td>{{object.Issued_date}}</td>
                        <td>{{object.returned}}</td>
                        <td>{{object.returned_data}}</td>
                        <td><a type="button" class="btn btn-primary" style="border-radius: 20px;" href= "{{object.id}}/detail">Detail</a></td>
                        <td><a type=" button " class = "btn btn-success" style="border-radius: 20px;" href ="{{object.id}}/update" >Update</a></td>
                        <td><a type = "button" class="btn btn-danger" style="border-radius: 20px;" href="{{object.id}}/delete">Delete</a></td>
                        {% endfor %}
                      </tr>
                     
                    </tbody>
                  </table>
        
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- /clients -->
  

    {% endblock %}    
</body>
</html>