demo/urls.py
from django.urls import path
from demo import views
from demo.views import TrainerCreateView, TrainerUpdateView
app_name = "demo"

urlpatterns = [
    path('home', views.home, name = 'home'),
    # path('', views.home, name = 'home'),
    path('blog', views.blog, name = 'blog'),
    path('about', views.about, name = 'about'),
    path('portfolio', views.portfolio, name = 'portfolio'),
    path('contact', views.contact, name = 'contact'),
    path('blogsingle/<id>', views.blogsingle, name = 'blogsingle'),
    path('training', views.training, name = 'training'),
    path('trainingdetails/<id>', views.trainingdetails, name = 'trainingdetails'),
    path('TrainerCreateView', TrainerCreateView.as_view(), name = 'TrainerCreateView'),
    path('<pk>/trainer', TrainerUpdateView.as_view(), name = 'trainer'),
]


# home, about, blog, portfolio, contact, blogsingle

tempaltedemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from demo import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls', namespace = 'demo')),
    path('', views.home, name = 'home'),
    # path('', views.home, name = 'home'),
    path('library/', include('library.urls', namespace = 'library')),
    path('shop/', include('shop.urls', namespace = 'shop')),
    path('landingpage/', include('landingpage.urls', namespace = 'landingpage')),
    path('photography/', include('photography.urls', namespace = 'photography')),
    path('restaurant/', include('restaurant.urls', namespace = 'restaurant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length = 200)
    days = models.IntegerField()
    syllabus1 = models.TextField(null = True, blank = True)
    syllabus2 = models.TextField(null = True, blank = True)
    syllabus3 = models.TextField(null = True, blank = True)
    syllabus4 = models.TextField(null = True, blank = True)
    syllabus5 = models.TextField(null = True, blank = True)
    syllabus6 = models.TextField(null = True, blank = True)
    syllabus7 = models.TextField(null = True, blank = True)
    syllabus8 = models.TextField(null = True, blank = True)
    syllabus9 = models.TextField(null = True, blank = True)
    syllabus10 = models.TextField(null = True, blank = True)
    syllabus11 = models.TextField(null = True, blank = True)
    syllabus12 = models.TextField(null = True, blank = True)
    syllabus13 = models.TextField(null = True, blank = True)
    syllabus14 = models.TextField(null = True, blank = True)
    syllabus15 = models.TextField(null = True, blank = True)
    syllabus16 = models.TextField(null = True, blank = True)
    syllabus17 = models.TextField(null = True, blank = True)
    syllabus18 = models.TextField(null = True, blank = True)
    syllabus19 = models.TextField(null = True, blank = True)
    syllabus20 = models.TextField(null = True, blank = True)
    
    def __str__(self):
        return self.name
    
class Blog(models.Model):
    name = models.CharField(max_length = 200)
    message1 = models.TextField(null = True, blank = True)
    message2 = models.TextField(null = True, blank = True)
    message3 = models.TextField(null = True, blank = True)
    message4 = models.TextField(null = True, blank = True)
    message5 = models.TextField(null = True, blank = True)
    message6 = models.TextField(null = True, blank = True)
    message7 = models.TextField(null = True, blank = True)
    message8 = models.TextField(null = True, blank = True)
    message9 = models.TextField(null = True, blank = True)
    message10 = models.TextField(null = True, blank = True)
    message11 = models.TextField(null = True, blank = True)
    message12 = models.TextField(null = True, blank = True)
    message13 = models.TextField(null = True, blank = True)
    message14 = models.TextField(null = True, blank = True)
    message15 = models.TextField(null = True, blank = True)
    message16 = models.TextField(null = True, blank = True)
    message17 = models.TextField(null = True, blank = True)
    message18 = models.TextField(null = True, blank = True)
    message19 = models.TextField(null = True, blank = True)
    message110 = models.TextField(null = True, blank = True)
    
    pictures = models.ImageField(upload_to = 'images', null = True, blank = True)
    def __str__(self):
        return self.name

    
class Team(models.Model):
    name = models.CharField(max_length = 200)
    expertise = models.CharField(max_length = 50)
    experience = models.IntegerField()
    pictures = models.ImageField(upload_to = 'images', null = True, blank = True)
    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length = 200)
    email = models.EmailField(max_length = 254, null = True, blank = True)
    mobile_number = models.IntegerField(null = True, blank = True)
    college_name = models.CharField(max_length =100, null = True, blank = True)
    message = models.TextField()
    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length = 200)
    description = models.TextField(null = True, blank = True)
    def __str__(self):
        return self.name

demo/forms.py
from django.forms import ModelForm

from demo.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

demo/views.py
from django.shortcuts import render, redirect
from demo.models import Project, Blog, Team, Contact
from demo.models import Course
from demo.forms import ContactForm


# Create your views here.
def home(request):
    course = Course.objects.all()
    training = Project.objects.all()
    # context = {'training': training, }
    context = { 'training': training,'course': course, }
    return render(request, 'demo/themes/home.html', context)

def about(request):
    team = Team.objects.all()
    context = {'team': team}
    return render(request, 'demo//themes/about.html', context)

def blog(request):
    blog = Blog.objects.all()
    context = {'blog': blog}
    return render(request, 'demo//themes/blog.html', context)

def portfolio(request):
    return render(request, 'demo//themes/portfolio.html')

def contact(request):    
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # name = form.cleaned_data.get('name')
            # email = form.cleaned_data.get('email')
            # mobile_number = form.cleaned_data.get('mobile_number')
            # college_name = form.cleaned_data.get('college_name')
            # msg = form.cleaned_data.get('msg')
            # return redirect('demo:portfolio')
            return redirect('/demo/home')
    context = {'form': form}
    return render(request, 'demo//themes/contact.html', context)
    # return render(request, 'demo//themes/contact.html')

def blogsingle(request, id):
    blog = Blog.objects.get(id = id)
    blog1= Blog.objects.all()
    context = {'blog': blog, 'blog1': blog1}
    return render(request, 'demo//themes/blogsingle.html', context)

def training(request):
    training = Project.objects.all()
    # context = {'training': training}
    course = Course.objects.all()
    context = {'training': training, 'course': course}
    return render(request, 'demo//themes/training.html', context)



def trainingdetails(request, id):
    training = Project.objects.get(id=id)
    context = {'training': training}
    course = Course.objects.all()
    context = {'training': training, 'course': course}
    return render(request, 'demo//themes/trainingdetails.html', context)

from django.views.generic import CreateView,  UpdateView

class TrainerCreateView(CreateView):
    model = Team
    fields = '__all__'
    template_name = 'demo/themes/cbv/create.html'
    success_url = '/demo/home'

class TrainerUpdateView(UpdateView):
    model = Team
    fields = '__all__'
    template_name = 'demo/themes/cbv/update.html'
    success_url = '/demo/home'
    

demo/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Kross - Creative Portfolio Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Creative Portfolio Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Kross Template v1.0">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- Drop down menu coloura -->

</head>
<body>
  

<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand font-tertiary h3" href="{% url 'demo:home' %}"><img src="{% static 'img/log.png' %}" alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'demo:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:about' %}">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:blog' %}">Django</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:portfolio' %}">Portfolio</a>
        </li>         -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:training' %}">Training</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:contact' %}">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle navbar-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  >
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #41228E;">
            <a class="dropdown-item" href="{% url 'library:home' %}" style = "background-color: #41228E; color:white ">Library</a>
            <a class="dropdown-item" href="{% url 'shop:home' %}" style = "background-color: #41228E; color:white;">Shop</a>
            <a class="dropdown-item" href="{% url 'landingpage:home' %}" style = "background-color: #41228E; color:white;">Landing Page</a>
            <a class="dropdown-item" href="{% url 'photography:home' %}" style = "background-color: #41228E; color:white;">Photography</a>
            <!-- <a class="dropdown-item" href="{% url 'shop:home' %}" style = "background-color: #41228E; color:white;">Library</a> -->
            <a class="dropdown-item" href="{% url 'restaurant:home' %}" style = "background-color: #41228E; color:white;">Restaurant</a>
            
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- page title -->
{% block title %}

{% endblock %}

  
<!-- contact -->

<!-- <section class="section section-on-footer" data-background="{% static 'images/backgrounds/bg-dots.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">Contact Form</h4>
          <form action="#" class="row">
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4"
                placeholder="Type Message Here" required></textarea>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button class="btn btn-primary w-100">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section> -->

<!-- /contact -->

<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">vijayamurugan2172@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">+91-9715449095</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">Anna Nagar west Extension, Chennai -600101</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <!-- <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="{% static 'Themefisher' %}">NLT</a></p> -->
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

demo/templates/base1.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Kross - Creative Portfolio Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Creative Portfolio Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Kross Template v1.0">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- Drop down menu coloura -->

</head>
<body>
  

<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand font-tertiary h3" href="{% url 'demo:home' %}"><img src="{% static 'img/log.png' %}" alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'demo:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:about' %}">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:blog' %}">Django</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:portfolio' %}">Portfolio</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:training' %}">Training</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'demo:contact' %}">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle navbar-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  >
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #41228E;">
            <a class="dropdown-item" href="{% url 'library:home' %}" style = "background-color: #41228E; color:white ">Library</a>
            <a class="dropdown-item" href="{% url 'shop:home' %}" style = "background-color: #41228E; color:white;">Shop</a>
            <a class="dropdown-item" href="{% url 'landingpage:home' %}" style = "background-color: #41228E; color:white;">Landing Page</a>
            <a class="dropdown-item" href="{% url 'photography:home' %}" style = "background-color: #41228E; color:white;">Photography</a>
            <!-- <a class="dropdown-item" href="{% url 'shop:home' %}" style = "background-color: #41228E; color:white;">Library</a> -->
            <a class="dropdown-item" href="{% url 'restaurant:home' %}" style = "background-color: #41228E; color:white;">Restaurant</a>
            
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- page title -->
{% block title %}

{% endblock %}

 <!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">vijayamurugan2172@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">+91-9715449095</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">Anna Nagar west Extension, Chennai -600101</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <!-- <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="{% static 'Themefisher' %}">NLT</a></p>
      
      <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="{% static 'Themefisher' %}">NLT</a></p> -->
  </div>
</footer>
<!-- /footer -->
 
<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>